version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-2:349769753356:task-definition/strapi-task:39
        LoadBalancerInfo:
          ContainerName: strapi
          ContainerPort: 1337